---
- name: Install and configure Apache2 web server
  hosts: webservers
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a custom index.html
      copy:
        content: "<h1>Welcome to Apache2 installed by Ansible!</h1>"
        dest: /var/www/html/index.html
